define([
	"transitions/dissolve_css",
	"transitions/cover_css",
	"transitions/cube_css",
	"transitions/reveal_css",
	"transitions/slidev_css",
	"transitions/coverv_css",
	"transitions/revealv_css",
	"transitions/swirl_css",
	"transitions/scaleOut_css",
	"transitions/scaleIn_css",
	"transitions/swap_css",
	"transitions/zoomOut_css",
	"transitions/zoomIn_css"
]);
