// Listing of all the deliteful functional tests
define([
	"./Accordion",
	"./Button",
	"./Checkbox",
	"./Combobox",
	"./ComboPopup",
	"./features",
	"./list/all",
	"./ScrollableContainer",
	"./Select",
	"./SidePane",
	"./Slider",
	"./StarRating",
	"./SwapView",
	"./Switch",
	"./Toaster",
	"./Tooltip",
	"./TooltipDialog"
]);
