//Listing of all the deliteful unit tests
define([
	"./LinearLayout-direction",
	"./LinearLayout-horizontal",
	"./LinearLayout-horizontal-3width",
	"./LinearLayout-horizontal-mixedwidth",
	"./LinearLayout-vertical",
	"./SidePane",
	"./ViewStack",
	"./ViewStack-prog",
	"./ScrollableContainer",
	"./StarRating",
	"./list/List",
	"./list/DefaultStore",
	"./list/Selection",
	"./list/Categories",
	"./ProgressBar",
	"./ProgressIndicator",
]);
