//Listing of all the deliteful unit tests
define([
	"./LinearLayout1",
	"./LinearLayout2",
	"./LinearLayout3",
	"./LinearLayout4",
	"./LinearLayout5",
	"./SidePane",
	"./ViewStack",
	"./ViewStack-prog",
	"./ScrollableContainer",
	"./StarRating",
	"./list/List",
	"./list/DefaultStore",
	"./list/Selection",
	"./list/Categories",
	"./ProgressBar",
	"./ProgressIndicator",
]);
